// <auto-generated />
namespace BuzzFeedAndy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QuizTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201711172204320_QuizTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
